// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljqzangmlgzkuzqatyqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqcXphbmdtbGd6a3V6cWF0eXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwODA2MTIsImV4cCI6MjA1MzY1NjYxMn0.fgKJw85iLa_-psDGSFHqgU1nVLSQ5Qu4ueKb9COycrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);